### ISSUE TITLE
Incompatible with HOOBS?

### ISSUE THREAD

**Issue by seanfletchr** [fjs21/homebridge-kumo#10]
After installing homebridge-kumo via HOOBS, I can configure the settings, but after homebridge restarts, the following appears in the logs:

```
10/5/2020, 1:18:00 PM homebridge API version: 2.5
[...]
10/5/2020, 1:18:01 PM Loaded plugin "homebridge-kumo".
[...]
10/5/2020, 1:18:01 PM The requested platform "Kumo" was not registered by any plugin.
10/5/2020, 1:18:01 PM Your config.json is requesting the platform "Kumo" which has not been published by any installed plugins.
```

**Comment by fjs21** [comment]
Based on the log, it sounds like the Kumo plugin is not properly installed. I don't use HOOBS so I have no way of troubleshooting this unfortunately. Perhaps another HOOBS user or HOOBS themselves could give you some support. I'd be happy to accept a pull request to fix this issue.

**Comment by seanfletchr** [comment]
After updating to the latest version of HOOBS, the Kumo plug-in now loads correctly.
