### ISSUE TITLE
Unclear from Documentation: Does this handle Multiple Units?

### ISSUE THREAD

**Issue by djc-msb** [fjs21/homebridge-kumo#12]
I'm installing a new system in a large house.

I've been quoted a system with 2 heat pumps outside and as many as 9 inside units (several of which will be paired).

Each unit will have its own PAC-UWHS002-WF-1.

Will I be able to see/interact-with each unit separately through HomeKit?

What features will I be able to control?

Thanks,

Dan Charles
New Orleans, LA
(504) 322-4648
Dan@DanCharles.org

**Comment by fjs21** [comment]
Hi, I only have one unit myself but the plugin is designed to support multiple units which report to/from the Kumo cloud. Once the plugin has that information (IP/serial) it will then control each via a direct request. I have had reports from others that have had two units successfully connected so it should work. If not, I can work with you to fix any bugs. Cheers, Fraser

**Comment by derk1127** [comment]
I have two outside heat exchanger units with six headunits on the inside. It is able to control each unit individually.
