### ISSUE TITLE
Cant change room in HomeKit

### ISSUE THREAD

**Issue by Arlington1984** [fjs21/homebridge-kumo#14]
The plugin appears to work fine other than all 5 units default to the default room and thereafter they cant be moved.  
When in Homekit i attempt to change the room the unit is allocated to, it rejects the attempt and returns the selection back to the default room. 

11/29/2020, 10:16:06 AM [Kumo] Kumo API: Successfully connected to the Kumo API.11/29/2020, 10:16:06 AM [Kumo] Number of devices found: 511/29/2020, 10:16:06 AM [Kumo] Restoring existing accessory from cache: Bedroom11/29/2020, 10:16:06 AM [Kumo] Restoring existing accessory from cache: Dining Room11/29/2020, 10:16:06 AM [Kumo] Restoring existing accessory from cache: Study11/29/2020, 10:16:06 AM [Kumo] Restoring existing accessory from cache: Living Room11/29/2020, 10:16:06 AM [Kumo] Restoring existing accessory from cache: Master Bedroom

**Comment by fjs21** [comment]
By Homekit, do you mean the Home app on an iOS device or the website (homebridge-ui-x). When an accessory is first added it always defaults to the "default room" in the iOS Home app. I change the room assignment inside the Home app and I haven't had it revert back to the "default room" unless I deleted the accessory from the cache. This might be a plugin problem. I would like to hear from others if they share this issue or not.

**Comment by Arlington1984** [comment]
Hi
Yes, this is in the Home app on iOS ot iPadOS.  When added they all went to the default room (the ‘living room’).  It is at the point trying to change the room assignment inside the Home app that it reverts back. 
I tried to capture a video to explain:
https://share.icloud.com/photos/0RWEhta9EzKaU4nGVLEVkNNHw
