### ISSUE TITLE
Local IP Not Responding

### ISSUE THREAD

**Issue by JonGoldmanPlaybill** [fjs21/homebridge-kumo#18]
I am trying to do a local connect (since I cannot control fan speed or vane direction without local direct it appears).  I got errors that others have listed before, so I tried DHCP assignment of a static IP to the Unit.  It has the static IP, but now home bridge Kumo appears to be holding onto the old IP when it tries for direct connect.  How can I remove the unit and re-add?

**Comment by fjs21** [comment]
You should login to Homebridge UI and remove the accessory in the settings page. 

![image](https://user-images.githubusercontent.com/65719819/108256458-9018aa00-712b-11eb-8bab-0d10fbdb68f1.png)

You should be able to see how to remove an individual device or alternatively reset homebridge (not recommended).

**Comment by fjs21** [comment]
Then restart Homebridge and it will discover the deleted accessory and refresh with latest information.

**Comment by fjs21** [comment]
If it reassigns the old IP address then the Kumo cloud has not yet been updated and I suggest you try using the Kumo app to trigger an update.

**Comment by fjs21** [comment]
It's a pain but once you have the static setup and working, I haven't had the problem since (6+ months).

**Comment by JonGoldmanPlaybill** [comment]
Thanks much.. trying now.  I'm running Homebridge on a QNAP container, so the restart takes longer than I like and I can't do it directly from the UI.

**Comment by JonGoldmanPlaybill** [comment]
Actually I'm not seeing how to remove an individual device.. the suggestion in the UI is "You will need to remove the existing Homebridge accessory from the Home app manually."

Which file is the persistent accessory in so that I can force it to re-pair?

**Comment by JonGoldmanPlaybill** [comment]
Ok.. I actually reset the Kumo device and re-paired it to the Kumo cloud. I also uninstalled and reinstalled this plugin (thank you for all the work, btw, since I didn't say that before).  Now it has reinstalled the device again and it still will not connect direct, I get this in the console:
<img width="816" alt="Screen Shot 2021-02-17 at 3 05 18 PM" src="https://user-images.githubusercontent.com/25302527/108261402-9ad63d80-7131-11eb-9f58-da1517828c2e.png">

I see the device in the Home App again, but all I have is temp & mode & dehumidifier- nothing about vane position or fan speed.

**Comment by fjs21** [comment]
The vane control and speed are located in the heater/cooler accessory. Press and hold on the icon and then scroll to reveal the additional settings and more info.

**Comment by JonGoldmanPlaybill** [comment]
Yeah, they aren't there:
<img width="504" alt="Screen Shot 2021-02-17 at 10 00 01 PM" src="https://user-images.githubusercontent.com/25302527/108298824-93338a80-716b-11eb-8b34-d6d8cee062ce.png">
<img width="509" alt="Screen Shot 2021-02-17 at 9 59 51 PM" src="https://user-images.githubusercontent.com/25302527/108298833-962e7b00-716b-11eb-8353-1fa5fb748f27.png">

**Comment by fjs21** [comment]
Yeah when separated you can do hold press and scroll and you can see the fan and oscillate settings. 

When combined you have to click on the two accessory's and then do the hold press on just the heater/cooler to get to the fan. Very clunky. 

I admit this is sub optimal. Maybe I will revert to having a separate fan accessory...

**Comment by JonGoldmanPlaybill** [comment]
That might be better, there isn't a "automatic" setting for the fan, and there isn't actually "targeting" for the vanes.  I'm just putting these in on a full system that I got for the house.  Do you mind if I fork and play with some additional controls?  I also have two of the newer "iSee" units that have split vane controls as well, and I'd love to see what I can do with them.  (Also totally willing to clone, branch, and submit a pull request to you if I come up with anything good, if you prefer.)

**Comment by fjs21** [comment]
Please do! 

1. In regard to the vane controls, I couldn't see an appropriate accessory type in the API that would allow this. Right now, all it does is set to automatic is oscillate is set to false, and to oscillate if set to true. I couldn't see a good way to implement the other settings in the current Homekit API. 

2. Fan Speed. The fan is set to automatic when it is set to the left most position (0). It then goes manual when set above zero. The fan speed has six settings on the Kumo side and 0-100 on the Homekit side so we currently convert one to the other.

In terms of fork, please do. I'd also be happy to incorporate any pull requests that you submit. As you can see there are definitely some UI design issues and also the IP address issue that could be improved upon.

**Comment by fjs21** [comment]
(one last thing, the fanv2 accessory code is still in the source just commented out, clunky I know, but I really wasn't sure if I wanted to remove and I think for the next version, I will try having both the separate Fan Accessory and and fan speed in the Heater/Cooler accessory enabled - it should be pretty straightforward... famous last words)
