### ISSUE TITLE
Number of devices found: 0

### ISSUE THREAD

**Issue by joshmohrer** [fjs21/homebridge-kumo#2]
This is awesome, thanks for building. A real step forward.

Its not finding my device:
[8/7/2020, 12:04:35 PM] Homebridge is running on port 51826.
[8/7/2020, 12:04:36 PM] [Kumo] Kumo API: Successfully connected to the Kumo API.
[8/7/2020, 12:04:36 PM] [Kumo] Number of devices found: 0

I suspect its because its in a strangely named Zone? 
![IMG_8684](https://user-images.githubusercontent.com/440810/89666734-e7021480-d8a8-11ea-9e58-7805b96e7e03.PNG)

Thanks for your help!

**Comment by fjs21** [comment]
It could be. Can you turn on debugging in your Homebridge UI and see if you get a long JSON output which will contain a list of your devices and properties that are returned after a successful login.

**Comment by joshmohrer** [comment]
{
    device: null,
    token: 'd032995280d70fbc0eb959fcc14d7032',
    username: 'joshmohrer@gmail.com'
  },
  {
    installer_name: 'Torre',
    installer_number: '9145895519',
    lastUpdate: 1593182997511,
    sendAnalytics: 1
  },
  {
    children: [
      {
        '$$hashKey': 'object:3552',
        children: [],
        id: '1593182997512-552542726',
        label: 'Home',
        lastScheduleChange: 0,
        lastUpdate: 1593182997512,
        level: 2,
        zoneTable: {}
      },
      {
        '$$hashKey': 'object:3553',
        children: [],
        id: '1593183371993-4193505726',
        label: 'Katonah',
        lastScheduleChange: 0,
        lastUpdate: 1593183520187,
        level: 2,
        network: { name: 'MOHRER', password: '' },
        zoneTable: {
          '9X34P008G100112F': {
            '$$hashKey': 'object:3589',
            _isNew: true,
            _isRespondingLocally: true,
            _requestRescan: 1,
            address: '192.168.1.104',
            autoModeEnabled: true,
            cryptoKeySet: 'F',
            cryptoSerial: '012337d8b28512d0ee',
            desiredConditionStack: [],
            eqcStageThreeBacksupChannels: [Object],
            eqcUpdatedLocally: [Object],
            equipmentControllerSettings: {},
            errorHandler: [Object],
            firmwareVersion: '02.02.01',
            forceCloudUpdates: false,
            hasElectricHeatingOption: false,
            holdChanged: 0,
            kumoSensorSettings: null,
            label: 'Kitchen',
            lastAdapterUpdate: 1596816642446,
            lastUpdate: 1596817652101,
            ledDisabled: false,
            mac: 'd4:53:83:47:77:ef',
            maxHeatSetpoint: 31,
            mhk2Settings: [Object],
            minCoolSetpoint: 16,
            optimalStart: false,
            overrideSettings: [Object],
            password: 'rBlZTE+u3LypE8FU5A5omJZp1KGq72HnOhHaonnp',
            port: '80',
            programEventSettings: [Object],
            prohibits: [Object],
            prohibitsChanged: 0,
            reportedCondition: [Object],
            reportedInitialSettings: [Object],
            reportedProfile: [Object],
            roomTempOffset: 0,
            rssi: [Object],
            sendDesiredConditionsPending: false,
            sendDesiredConditionsTime: '2020-08-07T16:10:42.645Z',
            serial: '9X34P008G100112F',
            success: [],
            systemChangeoverEnabled: false,
            systemChangeoverSettings: [Object],
            timezone: 'America/New_York',
            unitType: 'ductless'
          }
        }
      }
    ],
    id: '1593182997509-1486463075',
    label: 'Home',
    lastScheduleChange: 0,
    lastUpdate: 1596911888179,
    level: 1,
    version: 177,
    zoneTable: {}
  },
  'no device token'
]
[8/7/2020, 2:38:08 PM] [Kumo] Kumo API: Successfully connected to the Kumo API.
[8/7/2020, 2:38:08 PM] [Kumo] Number of devices found: 0
[8/7/2020, 2:38:08 PM] [Kumo] Token: d032995280d70fbc0eb959fcc14d7032
[8/7/2020, 2:38:11 PM] [Config] Homebridge Config UI X v4.24.0 is listening on :: port 8581

**Comment by fjs21** [comment]
If you see version 1.1.0 in NPM now, you could give it a whirl. Let me know if it works.

**Comment by joshmohrer** [comment]
Bingo. You're a damn genius. Thank you!

**Comment by fjs21** [comment]
Great! I also just bumped to version to 1.1.1 to hide a lot of debug info that I was roughly working on for more rapid local control. 1.1.1 should have a lot less random console activity.
