### ISSUE TITLE
Feature Request: Display temp in Fahrenheit instead of Celsius option

### ISSUE THREAD

**Issue by link266** [fjs21/homebridge-kumo#20]
This is an amazing plugin!  Got it installed on my Hoobs box and connected to (and controlling) my new Mitsubishi split system in under 2 minutes... think that's some kind of Homebridge record for me and I have this plugin to thank!

One feature request... Would it be possible to add an option to change the temp display in HomeKit from Celsius to Fahrenheit?  Totally understand Celsius being the default but would be nice for those of us more used to Fahrenheit.  I'd imagine this would be some sort of flag to change in the Homebridge Config UI (or in the JSON itself)... either way would work!

Thanks for considering!  I can't contribute any code to help out but will gladly test out and provide feedback on an updated build.

**Comment by fjs21** [comment]
This is controlled by either the UI if you are referring to the temperature displayed on the Homebridge web page or the Home app.

The device only communicates in Celsius. So the log will only contain celsius.

**Comment by link266** [comment]
Hi @fjs21, thanks for your reply!  I am specifically asking about the temp displayed in the Home app (not the Homebridge log).  See attached screenshots... even though the Homebridge web interface (Hoobs box) shows the temp in F the iOS Home app shows it in C.  This seems like I've configured something wrong but I've specifically set my Homebridge settings to display F and all other official HomeKit sensors I have show their temps in F.  Strange huh?

<img width="258" alt="Homebridge Web Interface - HVAC accessory" src="https://user-images.githubusercontent.com/10283117/116802367-00965c80-aac7-11eb-978d-8f95ac4c6cca.png">
<img width="816" alt="Homebridge Web Interface - Temp Settings" src="https://user-images.githubusercontent.com/10283117/116802370-012ef300-aac7-11eb-9e43-bd9a3ff050c6.png">
![HomeKit iPhone App Details 1](https://user-images.githubusercontent.com/10283117/116802371-012ef300-aac7-11eb-8166-b41bc91b501a.PNG)
![HomeKit iPhone App Details 2](https://user-images.githubusercontent.com/10283117/116802373-02602000-aac7-11eb-9bb4-dad8bd0cad90.PNG)
![HomeKit iPhone App Details 3](https://user-images.githubusercontent.com/10283117/116802375-02f8b680-aac7-11eb-84a1-7a115f2b0913.PNG)
![HomeKit iPhone App Room Page](https://user-images.githubusercontent.com/10283117/116802377-03914d00-aac7-11eb-828b-43529e8638e1.PNG)
![Kumo Cloud app](https://user-images.githubusercontent.com/10283117/116802379-04c27a00-aac7-11eb-93b2-99d9f18a75fb.PNG)
