### ISSUE TITLE
Exclude Device 

### ISSUE THREAD

**Issue by VeniceNerd** [fjs21/homebridge-kumo#21]
Love this plugin. So glad it’s finally possible to add Kumo to HomeKit!! 

Is it possible to exclude devices in the settings? I have a duplex and each side has an A/C unit, however, their are both linked to the same Kumo account. I would like to install two homebridge instances (one for each side) and then exclude one of the units from each side so not both show up in both homes. 

Is this possible?

Thanks for your work!

**Comment by fjs21** [comment]
This is a great idea! It should be implementable as I use a similar feature in other plugins such as Ring and myQ to separate devices into different homes. I'll add it to the to do list.

**Comment by VeniceNerd** [comment]
Very cool!!!! Can’t wait for the update and will def be donating to your project. It’s a godsend! :)

**Comment by fjs21** [comment]
This should be working in v1.6.0. See the release notes for more info.
