### ISSUE TITLE
Hi @fjs21, thanks for your reply!  I am specifically asking about the temp displayed in the Home app (not the Homebridge log).  See attached screenshots... even though the Homebridge web interface (Hoobs box) shows the temp in F the iOS Home app shows it in C.  This seems like I've configured something wrong but I've specifically set my Homebridge settings to display F and all other official HomeKit sensors I have show their temps in F.  Strange huh?

### ISSUE THREAD

**Issue by link266** [fjs21/homebridge-kumo#23]
Think maybe this comment below wasn't seen as the issue was already closed.  Totally possible I'm doing something wrong on my end but seems like even though everything else in my Homebridge setup displays in F the Kumo plugin still only shows C in the Home app.

Hi @fjs21, thanks for your reply!  I am specifically asking about the temp displayed in the Home app (not the Homebridge log).  See attached screenshots... even though the Homebridge web interface (Hoobs box) shows the temp in F the iOS Home app shows it in C.  This seems like I've configured something wrong but I've specifically set my Homebridge settings to display F and all other official HomeKit sensors I have show their temps in F.  Strange huh?
![HomeKit iPhone App Details 1](https://user-images.githubusercontent.com/10283117/116802394-1f94ee80-aac7-11eb-8eeb-b856de22867a.PNG)
![HomeKit iPhone App Details 2](https://user-images.githubusercontent.com/10283117/116802395-23287580-aac7-11eb-901b-0667b0454cd0.PNG)
![HomeKit iPhone App Details 3](https://user-images.githubusercontent.com/10283117/116802396-258acf80-aac7-11eb-894c-68eb3b6ea21d.PNG)
![HomeKit iPhone App Room Page](https://user-images.githubusercontent.com/10283117/116802400-27549300-aac7-11eb-92f9-7bebe75dd968.PNG)

<img width="816" alt="Homebridge Web Interface Temp Settings" src="https://user-images.githubusercontent.com/10283117/116802390-1a37a400-aac7-11eb-91dd-46c8bb84df5d.png">

<img width="258" alt="Homebridge Web Interface HVAC accessory" src="https://user-images.githubusercontent.com/10283117/116802386-16a41d00-aac7-11eb-8d8d-283d00d601ac.png">

_Originally posted by @link266 in https://github.com/fjs21/homebridge-kumo/issues/20#issuecomment-830740199_

**Comment by fjs21** [comment]
That's controlled by your iOS location settings. Nothing to do with Homebridge.
