### ISSUE TITLE
Duplicate Accessory

### ISSUE THREAD

**Issue by hansw1204** [fjs21/homebridge-kumo#25]
I love this plugin. Thank you so much.
After updating to the latest version the Dehumidifier Accessory is duplicated. The Fan accessory appears correctly as do all the others (Power, Heater/Cooler). Do I need to remove one instance?

**Comment by Yardorth** [comment]
Same happend to me after updating to v1.4.0.

**Comment by fjs21** [comment]
Thanks for posting this. I need to update the release notes for 1.4.0. You should delete the existing accessory in Homebridge UI to remove the duplicate Dehumidifier switch. When I added back the "PowerSwitch", I had to name the individual switches to allow multiple switches. A side effect of this is that the old "Dehumidifier" is essentially orphaned and you end up with a duplicate. 

I made the design decision a while back not to have the plugin reset the accessories on startup so you don't lose orphaned or removed accessories. This helps prevent accidental removal and then removal of all associated automations in your Home app.
