### ISSUE TITLE
New Device Showing as Fan Not Thermostat

### ISSUE THREAD

**Issue by ntableman** [fjs21/homebridge-kumo#28]
I am so glad you made this plugin, mine was nowhere near as good as this!

I am having an issue and wondering where to start to debug. I had to get a new wifi module, so had to add my unit to kumo again. When the new unit appeared in HomeKit after my homebridge 'saw' it, it came up as a fan, heater/cooler, dehumidifier, and general power switch. When these are grouped together (which is how I normally keep things) it appears as a fan, not a thermostat. So I cannot see the temperature in the tile anymore.

Any idea how I fix this?

![fish](https://user-images.githubusercontent.com/1039517/119650061-612c6700-bdf1-11eb-9add-a840dd6e9f20.png)

vs

<img width="124" alt="catdogfich" src="https://user-images.githubusercontent.com/1039517/119650253-9769e680-bdf1-11eb-8c8a-e54ae39082b0.png">

**Comment by fjs21** [comment]
Weird. Mine has the same temperature icon as the lower image in your post. But with the "4 off" text underneath. I tried playing with the settings and was unable to get the fan icon to appear. Do you recall what settings you had previously had to try to reproduce?

**Comment by fjs21** [comment]
I'm going to close. 

You might want to try the simpleDuctless accessory as that only involves the HeaterCooler. The downside is that you can't control the dehumidier using that.
