### ISSUE TITLE
Enhancement - Disable Fan, Power Switch, and Dehumidifier

### ISSUE THREAD

**Issue by mhoskins83** [fjs21/homebridge-kumo#32]
First I want to say thank you for creating this!

I have six Mini Splits that always stay in auto fan mode and each of those rooms have homekit enabled ceiling fans. With the recent update now when you call on Siri to turn the your ceiling fan on she say "which fan AC Fan or Master bedroom fan or all". Ultimately requiring you have to say the device name in each room you cant just say turn the fan on and the ceiling fan come on. 

Ask
Would it be possible on the plugin configuration to disable to fan selection mode, disable the power switch, dehumidifier?

So the homekit plugin would work as a thermostat only 
    When in Cool the system would turn on to Auto Fan 
    When in Heat the system would turn on to Auto Fan
    When in Off the system would shut down 

I would be willing to sponsor more than the dollar that GitHub is allowing.

**Comment by fjs21** [comment]
I could certainly give it a try. Maybe a switch in the configuration that would point to a different platform accessory. I'll add it to the todo list.

**Comment by fjs21** [comment]
This should be implemented in v1.5.1. Please reopen if you any issues.

**Comment by mhoskins83** [comment]
What you have done is awesome!

When changing to off state it changes to fan only then switches back to cooling


[Image.jpeg]



[Image.jpeg]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
