### ISSUE TITLE
Login failure / timeout even with correct account info

### ISSUE THREAD

**Issue by brad3d** [fjs21/homebridge-kumo#34]
I am able to login without trouble on the phone app and [Kumo Web App](https://app.kumocloud.com) using the same credentials. My house is 1 location with 6 units. 

When I try and login with hombridge-kumo plugin I get the fairly standard error message:

[Kumo] Kumo API: error - Time out on Kumo cloud connection.
[Kumo] Failed to login. Restart Homebridge to try again.

I switched the homebridge into debug mode to try and get more logs but it just gives the same error.  I tried turning connect directly on and off with reboots, no change. I checked my login info for capitalization and other common errors, no issue. I have several other plugins for other devices that are all working correctly. 
Homebridge is running Alpine Linux
Homebridge v1.3.4
Node.js Version  v14.17.1
From a Docker container.

json config: (L/P replaced for security)

{
    "username": "myRealEmailHere",
    "password": "myRealPasswordHere",
    "directAccess": true,
    "platform": "Kumo"
}

I do notice that the app and web app take a moment to login, perhaps the timeout is too short on the plugin? 
Is there an option on the plugin for more verbose debug output?

**Comment by monteroman** [comment]
I had the same issue with this plugin until I moved it to a child bridge and it started to work for me again.

**Comment by brad3d** [comment]
@monteroman  Thank you, this resolved the issue for me.

**Comment by fjs21** [comment]
@monteroman @brad3d Did either of you have homebridge-wemo installed on your main instance? Please see current discussion in #42

**Comment by brad3d** [comment]
I did not have wemo installed.

**Comment by monteroman** [comment]
I do have the Wemo plugin installed.
