### ISSUE TITLE
Set temp to Fahrenheit

### ISSUE THREAD

**Issue by sethlong1** [fjs21/homebridge-kumo#38]
Just installed the plugin to use with a new Kumo Cloud config and the temperature is appearing in HomeKit in Celsius. The temp in the Kumo app shows Fahrenheit. Is there a config setting to switch the plugin temp display to Fahrenheit?

**Comment by sethlong1** [comment]
Actually, upon further review, it looks like it’s not reporting the correct temp at all. It probably is in Fahrenheit but it’s showing 32 degrees instead of the actual 70 degrees that’s being reported by the actual Mitsubishi unit.

**Comment by link266** [comment]
I've been having this exact same issue as well.  I investigated for a bit a few months ago but couldn't make any progress towards fixing it.  

Have to ask... What makes you think that the plugin is indeed showing the temp in F (but just the incorrect temp degree)?  Curious how you figured that one out. :)

**Comment by sethlong1** [comment]
I was way off. It was showing in C but I found a setting to change it to F in Home. I had to open the bundle of 3 grouped accessories, then open the thermostat accessory to get to the C/F setting. 

That’s done, but any settings I make in the thermostat accessory (temp, mode) don’t stick. They reset back to mode: off when I come back to the Home app and the temp displays as 32, which is obviously incorrect in either F or C. The fan accessory setting is maintained between Home app launches, though.

**Comment by fjs21** [comment]
If you are seeing '32' that usually means the value being "read" is 0 and its just being converted in 32 by the C->F conversion. So there seems to be a problem somewhere. Can you turn on debugging and post your log? Remove anything private.

**Comment by sethlong1** [comment]
Here you go. Thanks!

[homebridge.log.txt](https://github.com/fjs21/homebridge-kumo/files/7227823/homebridge.log.txt)

**Comment by fjs21** [comment]
Thanks for the log. Your unitType is 'mvz' which I have not come across before. It seems to provide output similar to my 'ductless'. In v1.8.0, I have added the new unitType and it will use the template for the 'ductless' accessory which seems to be the same. Please test and let me know. Again posting any error logs would be great.

**Comment by sethlong1** [comment]
That definitely made a difference. I have a new set of accessories, including a “heater/cooler”. What’s confusing, though, is that I now see a total of 6 accessories (see attached screen shot). Is that expected?
![CA794F9D-0C44-4562-AF2F-488ACA809C14](https://user-images.githubusercontent.com/7230055/134754000-dc9da2f1-55ba-43f0-96ff-0da1d217f8c7.png)

**Comment by fjs21** [comment]
You need to go into the Homebridge UI and delete the old accessory. Let me know if you need more detailed instructions I have them in another previously resolved issue.

**Comment by sethlong1** [comment]
Got it. That seems to have worked! Thank you.
