### ISSUE TITLE
Power switch no longer working since latest version

### ISSUE THREAD

**Issue by Yardorth** [fjs21/homebridge-kumo#4]
I updated to v1.2.0 since then the power switch in HomeKit is no longer working and it is always in the off state. If I switch it on it will go back to off a few seconds later or when you switch out of Home app and back in. It’s no longer possible to shut down an unit the normal way, it only turns off if you turn the switch on and then off again very quickly. After the unit is off you can turn it back on by switching back to on but a few seconds later or switch out of Home app and back in the state of the switch goes back to off.

**Comment by fjs21** [comment]
I have been able to replicate the issue and am trying to locate the bug now.

**Comment by fjs21** [comment]
Should be fixed in v1.2.1

**Comment by Yardorth** [comment]
Thanks for the quick fix, it’s working flawlessly again.
