### ISSUE TITLE
Getting this error in the log every few seconds

### ISSUE THREAD

**Issue by hansw1204** [fjs21/homebridge-kumo#40]
[10/29/2021, 10:47:29 AM] [homebridge-kumo] Heater/Cooler: Unable to find target temp
[10/29/2021, 10:47:29 AM] [homebridge-kumo] {
  roomTemp: 21,
  mode: 'off',
  spCool: 27.5,
  spHeat: 22,
  vaneDir: 'auto',
  fanSpeed: 'auto',
  tempSource: 'sensor0',
  activeThermistor: 'sensor0',
  filterDirty: false,
  hotAdjust: false,
  defrost: false,
  standby: false,
  runTest: 0

**Comment by fjs21** [comment]
Hi, I've just published a new version which should patch this issue. Can you try v1.8.6?

**Comment by esetnik** [comment]
Having the same issue in v1.8.6:

 [11/3/2021, 5:46:01 PM] [homebridge-kumo] Heater/Cooler: Unable to find target temp

**Comment by fjs21** [comment]
Found the bug. Will fix shortly.

**Comment by fjs21** [comment]
Try v1.8.9

**Comment by esetnik** [comment]
I am having the same issue in v1.8.9

**Comment by fjs21** [comment]
I've been patching other bugs and we're at v1.8.15. The relevant log information is generated at startup and looks like:

> Initializing "%s" of unitType "%s" as generic (unspecified) unit.

In your cases, it should be followed by 

> %s: Found heat and cool settings will use ductless accessory

Let me know.

**Comment by esetnik** [comment]
v1.8.15 removes this error but seems to have broken the `directAccess` ability to connect:

```
04.11.21 11:08:38 (-0400)  main  [11/4/2021, 3:08:38 PM] [homebridge-kumo] queryDevice_Direct error: Time out on local IP connection..
04.11.21 11:08:38 (-0400)  main  [11/4/2021, 3:08:38 PM] [homebridge-kumo] Failed to connect to device IP (xxxxxxxx)
04.11.21 11:08:38 (-0400)  main  [11/4/2021, 3:08:38 PM] [homebridge-kumo] Disabling directAccess to Kumo devices
```

**Comment by hansw1204** [comment]
Interesting, I am on 1.8.15 as well but still get this:
[11/4/2021, 11:58:16 AM] [homebridge-kumo] Heater/Cooler: Unable to find target temp
However, I am using Direct Connect and that doesn't  seem to have a problem. I also can modify the target temperature in the Home app.

**Comment by fjs21** [comment]
> Interesting, I am on 1.8.15 as well but still get this:
> 
> [11/4/2021, 11:58:16 AM] [homebridge-kumo] Heater/Cooler: Unable to find target temp
> 
> However, I am using Direct Connect and that doesn't  seem to have a problem. I also can modify the target temperature in the Home app. 

Can you post your log so I can diagnose? Everything following a restart. Feel free to remove any parts you are uncomfortable sharing.

**Comment by hansw1204** [comment]
Here it is
[HB_Log.txt](https://github.com/fjs21/homebridge-kumo/files/7476820/HB_Log.txt)

**Comment by fjs21** [comment]
Looks like you have five units - all reporting as a ductless unitType. So they should be supported. 

Can you go into Homebridge UI and delete or the cached accessories associated with Kumo? Then restart.

**Comment by hansw1204** [comment]
I did remove cached accessories but the error remains. Also, the August Lock got kicked out but that’s another topic

Thanks for your help

 

 

 

From: Fraser Sim ***@***.***>
Reply-To: fjs21/homebridge-kumo ***@***.***>
Date: Friday, November 5, 2021 at 09:41
To: fjs21/homebridge-kumo ***@***.***>
Cc: Hans Winkler ***@***.***>, Author ***@***.***>
Subject: Re: [fjs21/homebridge-kumo] Getting this error in the log every few seconds (Issue #40)

 

Looks like you have five units - all reporting as a ductless unitType. So they should be supported.

Can you go into Homebridge UI and delete or the cached accessories associated with Kumo? Then restart.

**Comment by esetnik** [comment]
Sorry i'm still having this issue on v1.8.16

```
main  [11/5/2021, 6:19:23 PM] [homebridge-kumo] Heater/Cooler: Unable to find target temp
 main  [11/5/2021, 6:19:23 PM] [homebridge-kumo] {
 main    roomTemp: 18,
 main    mode: 'heat',
 main    spCool: 20.5,
 main    spHeat: 15.5,
 main    vaneDir: 'auto',
 main    fanSpeed: 'auto',
 main    tempSource: 'sensor0',
 main    activeThermistor: 'sensor0',
 main    filterDirty: false,
 main    hotAdjust: false,
 main    defrost: false,
 main    standby: false,
 main    runTest: 0
 main  }
 main  [11/5/2021, 6:19:23 PM] [homebridge-kumo] Heater/Cooler: Unable to find target temp
 main  [11/5/2021, 6:19:23 PM] [homebridge-kumo] {
 main    roomTemp: 18,
 main    mode: 'heat',
 main    spCool: 20.5,
 main    spHeat: 15.5,
 main    vaneDir: 'auto',
 main    fanSpeed: 'auto',
 main    tempSource: 'sensor0',
 main    activeThermistor: 'sensor0',
 main    filterDirty: false,
 main    hotAdjust: false,
 main    defrost: false,
 main    standby: false,
 main    runTest: 0
 main  }
``

**Comment by esetnik** [comment]
It looks like https://github.com/fjs21/homebridge-kumo/blob/b5cb33d8bdeea049ea80974ec75d50acc1e389b7/src/ductless.ts#L405 should be camelCased

**Comment by fjs21** [comment]
@esetnik Thanks! I merged the pull request and published a new version on npm with your fix. Good find!

**Comment by esetnik** [comment]
@fjs21 should I submit a PR for this one as well? https://github.com/fjs21/homebridge-kumo/blob/master/src/ductless_simple.ts#L301

**Comment by fjs21** [comment]
Actually. I need to double check. Not everything makes sense with Kumo json responses.

**Comment by esetnik** [comment]
I upgraded to v1.8.17 and I am no longer getting the console error, also my temp is now reading correctly. Thanks for your hard work on this plugin!

**Comment by hansw1204** [comment]
Yes, 1.8.17 fixed everything for me. Thanksyou so much
