### ISSUE TITLE
Potential conflict with homebridge-wemo plugin

### ISSUE THREAD

**Issue by esetnik** [fjs21/homebridge-kumo#42]
I'm getting the following error after setting up the homebridge-kumo config. Initially I was able to access my ductless via the plugin but after restarting homebridge I repeatedly receive the error that it timed out connecting to kumo cloud. I don't know why this is the case. FWIW the kumo cloud app on my phone is able to login and control my ductless just fine from the same network.

```
 main  [10/30/2021, 7:37:44 PM] [Kumo] Kumo API: error - Time out on Kumo cloud connection.
 main  [10/30/2021, 7:37:44 PM] [Kumo] Failed to login. Restart Homebridge to try again.
```

**Comment by fjs21** [comment]
This is usually due to a problem with your username and password. The plugin was unable to get a security token. Please check in your config that it is set correctly. Once you have updated your details you will need to restart home bridge for the plugin to try again.

**Comment by esetnik** [comment]
Username and password are both correct and I can use them to login on app.kumocloud.com. It looks like it could be a duplicate of https://github.com/fjs21/homebridge-kumo/issues/34. Should I attempt the solution from that issue?

**Comment by fjs21** [comment]
It does seem to be the same. I'd try the solution posted.

I was never able to replicate the issue so I have not been able to diagnose why it happens to only some users. The time out is set to 5 secs which should be enough unless your connection is very slow/unreliable. I could expose the time out to the user to make it available to set but if it's fixed via placing on a client bridge then great too!

**Comment by esetnik** [comment]
@fjs21 what's weird is it worked the first time I added this plugin but seems to have stopped working after I also added homebridge-wemo plugin. I wonder if there is some conflict between the two when running on the same bridge.

**Comment by fjs21** [comment]
Good theory. If you can test it, I can put a notice on the readme to warn other folks.

**Comment by esetnik** [comment]
It worked after adding the client bridge. The docs should probably be updated to reflect that this is necessary for some reason.
