### ISSUE TITLE
[Enhancement] Ducted Mitsubishi Mini Split Single Zone System

### ISSUE THREAD

**Issue by Cakedonut** [fjs21/homebridge-kumo#57]
Hello, thank you for creating this plugin! I'd love to get it working with the setup that I have in my home and can help provide any information, logging, debugging, etc that may help in that process.

I have a brand new Mitsubishi Multi-position Mini-split system. It is a ducted, single zone system. The model numbers are as follows: 
- Mitsubishi Hyper Heat unit SUZKA24NAHZ (heat pump on outside of home)
- Mitsubishi Universal Air Handler unit SVZKP24NA (fan system to circulate air through the ducts in the house)
- Mitsubishi MIA MHK2 PAC-USWHS002-WF-2 wireless controller connected to Kumo Cloud

I have installed the plugin and it is running successfully on my Homebridge setup. The logging says that it is able to connect and commands seem to be executed successfully whenever I tell Siri to "turn the heat up" to whatever degrees. Although, in the Kumo app, it doesn't reflect any of the changes so I'm not sure it is actually working correctly. And I also noticed that there are only settings for a "ductless" system, so that may be affecting things as well I'd imagine.

**Comment by fjs21** [comment]
To troubleshoot try setting temperatures using Siri and in the Home app. To see if it is working as intended. Wait about 30 secs and then check the Kumo app. It should propagate after about 30-60 secs. You may need to force close Kumo and reopen to see the update. 

If things aren't working as intended, take a look into the Homebridge log when you make a change using the Home app/Siri and you can see the commands being sent out. Note temps are always in C on the backend.

**Comment by Cakedonut** [comment]
I can see in the logs that it looks like things are working correctly:
`[03/02/2022, 22:38:52] [Kumo] Main (Heater/Cooler): set HeatingThresholdTemperature to 20.`

I have a schedule set up in the Kumo app that may just make the UX a little confusing since it seems to be heating the house up when I ask it to.

**Comment by Cakedonut** [comment]
Would it be helpful to provide any other information? I have the JSON payload that is served back from the Kumo cloud API that I can provide or any other logs that might be helpful.
