### ISSUE TITLE
Vent control

### ISSUE THREAD

**Issue by hansw1204** [fjs21/homebridge-kumo#58]
Not so much an issue but a question regarding vent control. In the Kumo app, I can set the vent position to a number of settings and the setting stays the same between runs (off-on) just controlled by the Kumo app. However, when I use a homekit automation, the vent setting seems to reset to 'automatic' between runs. Is there anything that can be done about this?
many thanks,
Hans

**Comment by fjs21** [comment]
It's really an implementation issue. The only available setting, that I could find in the Homebridge API, is swing mode which is a Boolean. So I decided to make it "auto" vs "swing". But the side effect will be that if you set another one of the modes via the Kump app it will get reset by the home app. 

I'll take a look to see if rather than sending "auto" to the device it just leaves it as-is. That way when you switch on swing it works and when you switch off swing it goes to auto but otherwise doesn't change the vent setting. Not sure if that is possible but I'll give it a look.

**Comment by hansw1204** [comment]
Thanks or looking into this. I am not sure it is the swing mode that is the issue. The swing mode can only be activated with the Mitsubishi remote (and not from the Kumo app) and it controls a vane that either is on (swinging horizontally back and forth) or it is inactive and then stays at the last position. I always keep that off and it correctly stays in the position I set it to with the remote. 

The vent mode I am talking about controls the vent that closes when the unit is off. It can be set to Auto, Ceiling, High, Middle, Low, Floor and Swing (moving vertically up and dow). This is the one I'd  like to keep at the preset position.

Many thanks

Hans

 

From: Fraser Sim ***@***.***>
Reply-To: fjs21/homebridge-kumo ***@***.***>
Date: Tuesday, February 8, 2022 at 15:03
To: fjs21/homebridge-kumo ***@***.***>
Cc: Hans Winkler ***@***.***>, Author ***@***.***>
Subject: Re: [fjs21/homebridge-kumo] Vent control (Issue #58)

 

It's really an implementation issue. The only available setting, that I could find in the Homebridge API, is swing mode which is a Boolean. So I decided to make it "auto" vs "swing". But the side effect will be that if you set another one of the modes via the Kump app it will get reset by the home app.

I'll take a look to see if rather than sending "auto" to the device it just leaves it as-is. That way when you switch on swing it works and when you switch off swing it goes to auto but otherwise doesn't change the vent setting. Not sure if that is possible but I'll give it a look.

**Comment by fjs21** [comment]
Sorry for the extreme delay. Try v1.8.23. I turned off the vane setting that occurs during power off and on setting. So it should retain the previous setting unless it is toggled in the Home app.

**Comment by hansw1204** [comment]
Thank you very much!

 

From: Fraser Sim ***@***.***>
Reply-To: fjs21/homebridge-kumo ***@***.***>
Date: Monday, March 7, 2022 at 21:58
To: fjs21/homebridge-kumo ***@***.***>
Cc: Hans Winkler ***@***.***>, Author ***@***.***>
Subject: Re: [fjs21/homebridge-kumo] Vent control (Issue #58)

 

Sorry for the extreme delay. Try v1.8.23. I turned off the vane setting that occurs during power off and on setting. So it should retain the previous setting unless it is toggled in the Home app.
