### ISSUE TITLE
Fahrenheit off

### ISSUE THREAD

**Issue by urbanhaas** [fjs21/homebridge-kumo#71]
So I read somewhere on this project that Kumo stores things in Celsius. I see HomeKit being off by a degree or two from the Kumo app.

Is this a precision thing? I see in Homebridge Accessories tiles that the degree at least shows it to tenths of a degree. Is there a way to forward that greater precision, or round appropriately? (float/double vs. integer precision?)

**Comment by fjs21** [comment]
Yeah, temperatures are stored in Celsius on the back end and then weirdly converted to Fahrenheit by the Kumo software. The plugin uses the native Celsius value and is converted by the HomeKit/Home App.
