### ISSUE TITLE
Published version inconsistency

### ISSUE THREAD

**Issue by esetnik** [fjs21/homebridge-kumo#75]
What is the actual latest version of this package?

- Current master branch commit has v1.8.24 as version in package.json
- github lists v1.10.1 as latest release
- npm is showing 1.10.0 as the latest published version

**Comment by fjs21** [comment]
My bad. I had made a mistake with the release number on GitHub and I hadn't pushed the last commit from my development box to GitHub.

It should be 1.10.0 as shown on npm.
