### ISSUE TITLE
Enable Dry mode

### ISSUE THREAD

**Issue by burtherman** [fjs21/homebridge-kumo#86]
Is it possible to enable HomeKit to control the “Dry” mode?

**Comment by fjs21** [comment]
Are you using the simple version? 
<img width="376" alt="image" src="https://github.com/fjs21/homebridge-kumo/assets/65719819/2910e57d-a258-42c7-9e9a-6ce98a874596">

If this is unchecked in your config, try unchecking and you'll hopefully you'll see the dehumidifier settings appear.
